enum authorities {
  USER_MODIFY = "USER_MODIFY",
  USER_DEACTIVATE = "USER_DELETE",
  USER_CREATE = "USER_PROFILE_CREATE",
  USER_READ = "USER_PROFILE_READ",
  PROFILE_EDIT = "USER_PROFILE_MODIFY",
  LIST_MANAGE = "USER_PROFILE_LIST_READ",
  DEFAULT = "DEFAULT",
}

export default authorities;