enum authorities {
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  CATEGORY_MANAGE = "CATEGORY_MANAGE",
  LIST_MANAGE = "LIST_MANAGE",
  PROFILE_EDIT = "PROFILE_EDIT",
  USER_DEACTIVATE = "USER_DEACTIVATE",

}

export default authorities;