name: Build
on: [push]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          cache-dependency-path: "react_frontend/yarn.lock"

      - name: Install dependencies
        working-directory: react_frontend
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: react_frontend
        run: yarn test

      - name: Build the app
        working-directory: react_frontend
        run: yarn build --production
